/* [PH] Kalambury — WORD POOLS (oddzielny plik)
   Uwaga: trzymamy w window, bo projekt nie używa modułów ES.
   Update: +200 haseł do każdej kategorii.
*/
(function(){
  'use strict';
  window.KALAMBURY_WORD_POOLS = {
    classic:[
    'Krzesło','Okulary','Telefon','Samolot','Wiatrak','Szachy','Młotek','Wulkan','Parasol','Lustro',
    'Zegar','Latarka','Plecak','Kalendarz','Nożyczki','Miotła','Odkurzacz','Pralka','Czajnik','Toster',
    'Pilot do TV','Kamera','Myszka komputerowa','Klawiatura','Monitor','Ładowarka','Powerbank','Słuchawki','Głośnik bluetooth','Kabel USB',
    'Przedłużacz','Listwa zasilająca','Bateria','Żarówka','Świeczka','Zapałki','Zapalniczka','Termometr','Apteczka','Plaster',
    'Bandaż','Maseczka','Okulary przeciwsłoneczne','Czapka z daszkiem','Szalik','Rękawiczki','Kurtka','Płaszcz','Kalosze','Buty sportowe',
    'Skarpetki','Pasek','Portfel','Moneta','Banknot','Karta płatnicza','Bilet','Dowód osobisty','Paszport','Klucze',
    'Brelok','Kłódka','Zamek błyskawiczny','Guzik','Igła i nitka','Maszyna do szycia','Wieszak','Szafa','Komoda','Szuflada',
    'Łóżko','Poduszka','Kołdra','Prześcieradło','Materac','Lampa','Lampka nocna','Zasłona','Roleta','Dywan',
    'Wycieraczka','Kosz na śmieci','Worek na śmieci','Mop','Gąbka','Ścierka','Płyn do naczyń','Szczotka','Grzebień','Szczoteczka do zębów',
    'Pasta do zębów','Mydło','Szampon','Suszarka do włosów','Prostownica','Golarka','Krem do rąk','Perfumy','Dezodorant','Ręcznik',
    'Wanna','Prysznic','Umywalka','Toaleta','Papier toaletowy','Chusteczki','Słoik','Butelka','Kubek','Filiżanka',
    'Szklanka','Talerz','Miska','Widelec','Nóż','Łyżka','Łyżeczka','Deska do krojenia','Patelnia','Garnek',
    'Pokrywka','Durszlak','Tarka','Wałek do ciasta','Mikser','Blender','Lodówka','Zamrażarka','Piekarnik','Mikrofalówka',
    'Zmywarka','Ekspres do kawy','Młynek do kawy','Cukiernica','Solniczka','Pieprzniczka','Czajniczek','Termos','Bidon','Korkociąg',
    'Otwieracz do puszek','Sitko','Lejek','Waga kuchenna','Miarka','Zeszyt','Notatnik','Książka','Gazeta','Magazyn',
    'Folder reklamowy','Katalog','Mapa','Kompas','Linijka','Cyrkiel','Kalkulator','Długopis','Ołówek','Gumka',
    'Temperówka','Zakreślacz','Spinacz','Zszywacz','Dziurkacz','Taśma klejąca','Klej','Marker','Tablica','Kreda',
    'Gąbka do tablicy','Piórnik','Pudełko','Szufelka','Łopatka','Grabie','Łopata','Miarka budowlana','Poziomica','Wiertarka',
    'Wkrętarka','Śrubokręt','Klucz francuski','Klucz imbusowy','Piła','Gwoździe','Śruby','Taśma miernicza','Drabina','Taczka',
    'Konewka','Doniczka','Ziemia do kwiatów','Nasiona','Sekator','Wąż ogrodowy','Spryskiwacz','Parawan','Rękawice robocze','Kask',
    'Okulary ochronne','Kamizelka odblaskowa','Latarnia','Znak drogowy','Sygnalizacja świetlna','Rower','Hulajnoga','Deskorolka'
  ],
    movies:[
    'Titanic','Matrix','Shrek','Gladiator','Incepcja','Star Wars','Harry Potter','Avatar','Gwiezdne wojny','Władca Pierścieni',
    'Król Lew','Ojciec chrzestny','Pulp Fiction','Forrest Gump','Skazani na Shawshank','Terminator 2: Dzień sądu','Obcy','Szczęki','Jurassic Park','Powrót do przyszłości',
    'Piraci z Karaibów','Avengers: Koniec gry','Spider-Man: Bez drogi do domu','Batman: Mroczny Rycerz','Joker','Interstellar','Django','Bękarty wojny','Wielki Gatsby','Wilk z Wall Street',
    'Zielona mila','Braveheart','Rocky','Rambo','Indiana Jones','E.T.','Toy Story','Auta','Potwory i spółka','Kung Fu Panda',
    'Jak wytresować smoka','Madagaskar','Epoka lodowcowa','Kraina lodu','Vaiana','Coco','W głowie się nie mieści','Minionki','Gru, Dru i Minionki','Shrek 2',
    'Shrek Trzeci','Mad Max: Na drodze gniewu','Matrix Reaktywacja','Matrix Rewolucje','Memento','Prestiż','Doktor Strange','Iron Man','Kapitan Ameryka: Pierwsze starcie','Thor: Ragnarok',
    'Strażnicy Galaktyki','Czarna Pantera','Ant-Man','Deadpool','X-Men','Logan','Wolverine','Fantastyczna Czwórka','Wonder Woman','Aquaman',
    'Człowiek ze stali','Liga Sprawiedliwości','Szybcy i wściekli','Szybcy i wściekli 5','Szybcy i wściekli 7','Mission: Impossible','Mission: Impossible – Fallout','James Bond: Skyfall','James Bond: Casino Royale','07: Spectre',
    'John Wick','John Wick 2','John Wick 3','Jason Bourne','Tożsamość Bourne’a','Ultimatum Bourne’a','Szeregowiec Ryan','Pearl Harbor','Dunkierka','917',
    'Apocalypse Now','Czas apokalipsy','Pluton','Łowca jeleni','Lista Schindlera','Pianista','Chłopcy z ferajny','Kasyno','Dawno temu w Ameryce','American Beauty',
    'Fight Club','Siedem','Milczenie owiec','Hannibal','Psychoza','Lśnienie','To','Obecność','Annabelle','Naznaczony',
    'Egzorcysta','Dziecko Rosemary','Parasite','Oldboy','Spirited Away','Księżniczka Mononoke','Ruchomy zamek Hauru','Mój sąsiad Totoro','Akira','Ghost in the Shell',
    'Blade Runner','Blade Runner 2049','Diuna','Diuna: Część druga','Oblivion','Marsjanin','Grawitacja','Armageddon','Dzień Niepodległości','Transformers',
    'Transformers: Zemsta upadłych','Królestwo niebieskie','Troja','00','Robin Hood','Król Artur','Excalibur','Brave','Merida Waleczna','Zaplątani',
    'Królewna Śnieżka i siedmiu krasnoludków','Piękna i Bestia','Aladyn','Mulan','Herkules','Tarzan','Księga dżungli','Dumbo','Pinokio','Mała Syrenka',
    'Alicja w Krainie Czarów','Charlie i fabryka czekolady','Willy Wonka','Peter Pan','Hook','Niania McPhee','Paddington','Paddington 2','Miś','Seksmisja',
    'Chłopaki nie płaczą','Kiler','Kiler-ów 2-óch','Psy','Dzień świra','Rejs','Va banque','Vabank II','Kingsajz','C.K. Dezerterzy',
    'Sala samobójców','Bogowie','Ida','Zimna wojna','Boże Ciało','Wesele','Katyń','Quo Vadis','Ogniem i mieczem','Pan Tadeusz',
    'Potop','Krzyżacy','Czterej pancerni i pies','Stawka większa niż życie','Ranczo','Świat według Kiepskich','Rodzina zastępcza','Friends','The Office','Breaking Bad',
    'Gra o tron','Stranger Things','The Witcher','Sherlock','Narcos','Dom z papieru','Chernobyl','The Crown','Black Mirror','Dexter',
    'House','Dr House','Suits','Mad Men','The Mandalorian','Andor','Loki','WandaVision'
  ],
    music:[
    'Gitara','Pianino','Koncert','Mikrofon','DJ','Rock','Hip-hop','Perkusja','Skrzypce','Saksofon',
    'Trąbka','Flet','Wiolonczela','Kontrabas','Harfа','Akordeon','Harmonijka ustna','Bęben','Tamburyn','Marakasy',
    'Kastaniety','Talerze perkusyjne','Werbel','Bęben basowy','Ksylofon','Dzwonki','Ukulele','Banjo','Mandolina','Gitara basowa',
    'Syntezator','Keyboard','Fortepian','Organy','Wibrafon','Rytm','Melodia','Harmonia','Refren','Zwrotka',
    'Mostek','Chór','Soliści','Dyrygent','Orkiestra','Zespół rockowy','Zespół jazzowy','Big band','Festiwal','Backstage',
    'Bilety na koncert','Bis','Autograf','Statyw mikrofonowy','Głośniki','Wzmacniacz','Mikser audio','Kable XLR','Słuchawki','Odsłuch',
    'Studio nagrań','Nagrywanie','Miksowanie','Mastering','Sample','Loop','Bit','DJ set','Gramofon','Płyta winylowa',
    'Płyta CD','Kaseta magnetofonowa','Playlista','Radio','Podcast muzyczny','Teledysk','Klip muzyczny','Karaoke','Taniec','Breakdance',
    'Rap','Trap','Pop','Metal','Punk','Reggae','Ska','Disco','Disco polo','Techno',
    'House','EDM','Drum and bass','Dubstep','Jazz','Blues','Soul','R&B','Funk','Gospel',
    'Muzyka klasyczna','Opera','Operetka','Balet','Muzyka filmowa','Muzyka elektroniczna','Muzyka ambient','Muzyka folkowa','Muzyka góralska','Muzyka latino',
    'Salsa','Bachata','Tango','Walc','Polonez','Mazur','Kujawiak','Oberek','Kolęda','Pastorałka',
    'Hymn','Ballada','Sonata','Symfonia','Koncert fortepianowy','Aria','Uwertura','Partytura','Nuty','Klucz wiolinowy',
    'Pięciolinia','Metronom','Stroik','Strojenie','Próba zespołu','Jam session','Improwizacja','Solo gitarowe','Riff','Chwyty gitarowe',
    'Kapodaster','Kostka do gitary','Struny','Pałeczki perkusyjne','Pianissimo','Fortissimo','Tempo','Takt','Metrum','Skala muzyczna',
    'Tonacja','Transpozycja','Wokal','Falset','Chrypka','Chórki','Beatbox','Klapnięcie','Owacje','Publiczność',
    'Encore','The Beatles','Queen','Michael Jackson','Madonna','Elvis Presley','ABBA','U2','Coldplay','Metallica',
    'Nirvana','Pink Floyd','Led Zeppelin','AC/DC','The Rolling Stones','Linkin Park','Eminem','Drake','Taylor Swift','Beyoncé',
    'Rihanna','Adele','Ed Sheeran','Bruno Mars','Lady Gaga','The Weeknd','Daft Punk','David Guetta','Avicii','Calvin Harris',
    'Marshmello','Imagine Dragons','Billie Eilish','Kanye West','Jay-Z','Kendrick Lamar','Snoop Dogg','Pac','The Notorious B.I.G.','Bob Marley',
    'Shakira','Bad Bunny','Rosalía','BTS','BLACKPINK','Dua Lipa','Harry Styles','Arctic Monkeys'
  ],
    sports:[
    'Piłka nożna','Koszykówka','Tenis','Boks','Siatkówka','Maraton','Skoki narciarskie','Pływanie','Piłka ręczna','Hokej',
    'Rugby','Badminton','Golf','Szermierka','Łucznictwo','Strzelectwo','Judo','Karate','Taekwondo','Wspinaczka',
    'Gimnastyka','Triathlon','Kajakarstwo','Wioślarstwo','Narciarstwo alpejskie','Narciarstwo biegowe','Snowboard','Łyżwiarstwo szybkie','Łyżwiarstwo figurowe','Jeździectwo',
    'Skateboarding','Parkour','Crossfit','Podnoszenie ciężarów','Rzut oszczepem','Rzut dyskiem','Pchnięcie kulą','Skok w dal','Skok wzwyż','Bieg na 100 metrów',
    'Bieg na 400 metrów','Bieg na 1500 metrów','Bieg z przeszkodami','Bieg sztafetowy','Pięciobój nowoczesny','Biathlon','Bobsleje','Saneczkarstwo','Curling','Baseball',
    'Softball','Cricket','Futsal','Piłka wodna','Pływanie synchroniczne','Skoki do wody','Kolarstwo szosowe','Kolarstwo górskie','BMX','Motocross',
    'Rajd samochodowy','Formuła 1','Żużel','Kręgle','Bilard','Darts','Tenis stołowy','Squash','Padel','Siatkówka plażowa',
    'Koszykówka 3x3','Piłka nożna plażowa','Biegi narciarskie','Spływ kajakowy','Wędkarstwo sportowe','E-sport','Szachy','Poker sportowy','Walka MMA','Kickboxing',
    'Boks tajski','Zapasy','Sumo','Korfball','Ultimate frisbee','Frisbee','Rzut wolny','Rzut karny','Spalony','Rzut rożny',
    'Aut','Dogrywka','Rzuty karne','Kapitan drużyny','Sędzia','Czerwona kartka','Żółta kartka','Medal złoty','Medal srebrny','Medal brązowy',
    'Puchar','Mistrzostwa świata','Mistrzostwa Europy','Igrzyska olimpijskie','Rozgrzewka','Trening interwałowy','Stretching','Kontuzja','Rehabilitacja','Masaż sportowy',
    'Siłownia','Bieżnia','Hantle','Sztanga','Kettlebell','Skakanka','Worek bokserski','Mata do jogi','Ławeczka','Stoper',
    'Piłka','Kosz','Rakieta tenisowa','Piłeczka tenisowa','Piłka do siatkówki','Piłka do koszykówki','Kij hokejowy','Krążek','Łuk','Tarcza',
    'Strzała','Kask','Ochraniacze','Rękawice bokserskie','Kimono','Mata','Tatami','Buty piłkarskie','Korki','Spodenki sportowe',
    'Koszulka sportowa','Dres','Getry','Opaska kapitańska','Trybuny','Kibice','Fala na stadionie','Doping','Mecz','Set',
    'Gem','As serwisowy','Wolej','Bekhend','Forhend','Slam dunk','Rzut za trzy','Alley-oop','Blok','As w siatkówce',
    'Atak','Obrona','Przyjęcie','Rozgrywający','Libero','Spiker','Rozgrywka','Tabela wyników','Remis','Porażka',
    'Zwycięstwo','Rekord świata','Rekord życiowy','Finisz','Start','Meta','Przedbieg','Eliminacje','Półfinał','Finał',
    'Sparing','Liga','Play-off','Derby','Transfer','Kontrakt','Trener','Ławka rezerwowych','Zmiana zawodnika','Kontuzjowany',
    'Sprint','Wytrzymałość','Siła','Koordynacja','Refleks','Taktyka','Strategia','Fair play','Doping (zakazany)','Spiker stadionowy',
    'Tryb VAR','Oficjalny czas','Przerwa','Kwarta','Połowa','Runda','Etap','Wspinaczka na ściance'
  ],
    jobs:[
    'Lekarz','Strażak','Policjant','Programista','Kucharz','Pilot','Nauczyciel','Mechanik','Pielęgniarka','Ratownik medyczny',
    'Weterynarz','Dentysta','Farmaceuta','Psycholog','Fizjoterapeuta','Dietetyk','Prawnik','Sędzia','Prokurator','Notariusz',
    'Księgowy','Audytor','Analityk finansowy','Bankier','Doradca podatkowy','Makler','Ubezpieczyciel','Kasjer','Sprzedawca','Kierownik sklepu',
    'Magazynier','Kurier','Listonosz','Kierowca ciężarówki','Taksówkarz','Kierowca autobusu','Maszynista','Pilot samolotu','Stewardessa','Kontroler lotów',
    'Kapitan statku','Marynarz','Rybak','Strażnik miejski','Ochroniarz','Detektyw','Żołnierz','Straż graniczna','Celnik','Górnik',
    'Hutnik','Spawacz','Tokarz','Frezarz','Ślusarz','Mechanik samochodowy','Mechanik rowerowy','Elektryk','Elektronik','Automatyk',
    'Inżynier budownictwa','Architekt','Geodeta','Hydraulik','Monter','Stolarz','Cieśla','Murarz','Tynkarz','Glazurnik',
    'Dekarz','Malarz pokojowy','Ogrodnik','Rolnik','Sadownik','Leśnik','Weterynarz (mały)','Wychowawca','Pedagog','Bibliotekarz',
    'Naukowiec','Chemik','Biolog','Fizyk','Matematyk','Informatyk','Administrator sieci','Tester oprogramowania','Analityk danych','UX designer',
    'Grafik komputerowy','Fotograf','Operator kamery','Montażysta','Dźwiękowiec','Dziennikarz','Redaktor','Copywriter','Tłumacz','Lektor',
    'Aktor','Reżyser','Scenarzysta','Muzyk','DJ','Szef kuchni','Cukiernik','Piekarz','Rzeźnik','Kelner',
    'Barman','Barista','Sommelier','Hotelarz','Recepcjonista','Przewodnik turystyczny','Animator czasu wolnego','Trener personalny','Instruktor jogi','Ratownik wodny',
    'Kosmetyczka','Fryzjer','Barber','Stylista','Manikiurzystka','Makijażysta','Krawiec','Szewc','Jubiler','Zegarmistrz',
    'Kierowca rajdowy','Makler sztuki','Kurator wystaw','Projektant wnętrz','Dekorator','Florysta','Event manager','Organizator wesel','Trener psów','Behawiorysta zwierząt',
    'Opiekun osób starszych','Opiekunka do dzieci','Niania','Położna','Logopeda','Terapeuta zajęciowy','Ratownik górski','Polarnik','Geolog','Sejsmolog',
    'Meteorolog','Oceanograf','Astronom','Kosmonauta','Mechanik lotniczy','Lakiernik','Blacharz','Wulkanizator','Elektromechanik','Serwisant AGD',
    'Serwisant komputerów','Specjalista IT helpdesk','Konsultant call center','Pracownik biurowy','Sekretarka','Asystent zarządu','Specjalista HR','Rekruter','Trener szkoleń','Coach',
    'Mediator','Rzecznik prasowy','Specjalista PR','Marketingowiec','Specjalista SEO','Specjalista social media','Community manager','Product manager','Project manager','Scrum master',
    'Kierownik budowy','Inspektor BHP','Inspektor jakości','Kontroler biletów','Konduktor','Pracownik kolei','Pracownik lotniska','Bagażowy','Portier','Kierownik hotelu',
    'Pokojówka','Pracownik sprzątający','Pracownik ochrony','Ratownik na plaży','Instruktor nurkowania','Instruktor jazdy','Trener piłki nożnej','Trener siatkówki','Sędzia sportowy','Komentator sportowy',
    'Pisarz','Poeta','Ilustrator','Animator 2D','Animator 3D','Programista gier','Level designer','Sound designer'
  ],
    food:[
    'Pizza','Sushi','Pierogi','Lody','Burger','Spaghetti','Tort','Sałatka','Schabowy','Bigos',
    'Żurek','Barszcz czerwony','Zupa ogórkowa','Grochówka','Kapuśniak','Flaki','Gołąbki','Placki ziemniaczane','Kopytka','Kluski śląskie',
    'Pyzy','Racuchy','Faworki','Makowiec','Piernik','Babka','Szarlotka','Tiramisu','Panna cotta','Brownie',
    'Cheesecake','Pączki','Drożdżówka','Kremówka','Sernik','Gofry','Naleśniki','Omlet','Jajecznica','Jajko sadzone',
    'Tosty','Kanapka','Bagietka','Croissant','Bułka','Chleb','Bułeczki','Kiełbasa','Parówki','Boczek',
    'Szynka','Stek','Kotlet mielony','Kurczak pieczony','Skrzydełka BBQ','Nuggetsy','Ryba po grecku','Łosoś','Tuńczyk','Sushi maki',
    'Sashimi','Ramen','Pho','Pad thai','Curry','Tikka masala','Biryani','Falafel','Hummus','Kuskus',
    'Ryż smażony','Makaron carbonara','Makaron bolognese','Lasagne','Risotto','Gnocchi','Pierogi ruskie','Pierogi z mięsem','Pierogi z kapustą i grzybami','Pierogi na słodko',
    'Zapiekanka','Kebab','Burrito','Taco','Nachosy','Guacamole','Chili con carne','Sałatka grecka','Sałatka cezar','Sałatka jarzynowa',
    'Mizeria','Surówka z marchewki','Coleslaw','Ziemniaki puree','Frytki','Kasza gryczana','Kasza jaglana','Quinoa','Owsianka','Granola',
    'Jogurt','Kefir','Ser żółty','Ser feta','Mozzarella','Camembert','Parmezan','Masło','Oliwa','Sos pomidorowy',
    'Keczup','Majonez','Musztarda','Sos czosnkowy','Sos BBQ','Sos sojowy','Sos teriyaki','Dżem','Miód','Czekolada',
    'Kakao','Kawa latte','Kawa espresso','Herbata zielona','Herbata czarna','Lemoniada','Koktajl owocowy','Smoothie','Pierogi z truskawkami','Pierogi z jagodami',
    'Sernik na zimno','Galaretka','Budyń','Kisiel','Płatki kukurydziane','Pancakes','Waffle','Crêpe','Hot dog','Subway kanapka',
    'Wrap','Tortilla','Quesadilla','Enchilada','Fajita','Paella','Gazpacho','Tapas','Bruschetta','Caprese',
    'Minestrone','Ravioli','Tortellini','Pizza margherita','Pizza pepperoni','Pizza hawajska','Pizza quattro formaggi','Zupa miso','Onigiri','Tempura',
    'Bibimbap','Kimchi','Gyoza','Bao bun','Dim sum','Kaczka po pekińsku','Sajgonki','Banh mi','Ceviche','Empanada',
    'Arepa','Feijoada','Tost francuski','Jajka benedyktyńskie','Shakshuka','Hummus z papryką','Baba ghanoush','Tabbouleh','Szaszłyki','Grillowane warzywa',
    'Karkówka z grilla','Kiełbasa z ogniska','Żeberka','Gulasz','Boeuf bourguignon','Zrazy','Bitki','Kasza z sosem','Ryż z warzywami','Makaron z pesto',
    'Pesto','Tarta','Quiche','Leczo','Ratatouille','Fasolka po bretońsku','Bigos wegetariański','Tatar','Carpaccio','Śledź w śmietanie',
    'Sałatka z tuńczykiem','Sałatka z kurczakiem','Sałatka owocowa','Kokos','Ananas','Mango','Banany','Truskawki'
  ],
    places:[
    'Plaża','Las','Lotnisko','Muzeum','Kino','Góry','Zamek','Stadion','Teatr','Galeria handlowa',
    'Siłownia','Plac zabaw','Hotel','Schronisko','Camping','Kawiarnia','Restauracja','Poczta','Dworzec','Metro',
    'Most','Wyspa','Wodospad','Pustynia','Jaskinia','Zoo','Aquapark','Ratusz','Rynek','Stare Miasto',
    'Plac','Park','Ogród botaniczny','Sklep spożywczy','Supermarket','Apteka','Szpital','Przychodnia','Szkoła','Przedszkole',
    'Uniwersytet','Biblioteka','Księgarnia','Galeria sztuki','Opera','Filharmonia','Hala sportowa','Basen','Boisko','Kort tenisowy',
    'Lodowisko','Wesołe miasteczko','Karuzela','Wydmy','Szczyt górski','Schronisko górskie','Szlak','Polana','Jezioro','Rzeka',
    'Morze','Port','Marina','Latarnia morska','Klif','Molo','Promenada','Deptak','Targ','Bazar',
    'Targowisko','Stacja benzynowa','Warsztat samochodowy','Parking','Autostrada','Rondo','Przejście dla pieszych','Sygnalizacja świetlna','Terminal','Brama (gate)',
    'Wieża widokowa','Punkt widokowy','Pałac','Twierdza','Ruiny','Katedra','Kościół','Klasztor','Cmentarz','Kaplica',
    'Pomnik','Fontanna','Akwarium','Planetarium','Obserwatorium','Stacja kolejowa','Peron','Przystanek autobusowy','Tramwaj','Wieżowiec',
    'Biuro','Fabryka','Magazyn','Hurtownia','Plac budowy','Wioska','Wieś','Miasto','Osiedle','Blok',
    'Kamienica','Dom jednorodzinny','Balkon','Taras','Ogródek','Piwnica','Strych','Garaż','Gęsty las','Łąka',
    'Pole','Sad','Winnica','Wzgórze','Przystań','Plaża nudystów','Sauna','Łaźnia','Spa','Salon masażu',
    'Salon kosmetyczny','Fryzjer','Bank','Bankomat','Urząd skarbowy','Sąd','Komisariat','Remiza','Biblioteka miejska','Stadnina koni',
    'Stajnia','Wypożyczalnia rowerów','Wypożyczalnia kajaków','Sklep z zabawkami','Sklep sportowy','Sklep muzyczny','Sklep z elektroniką','Serwis telefonów','Paczkomat','Punkt ksero',
    'Kantor','Piekarnia','Cukiernia','Lodziarnia','Pizzeria','Bar mleczny','Food truck','Targ śniadaniowy','Nocny market','Stacja metra',
    'Zajezdnia tramwajowa','Zajezdnia autobusowa','Stacja kolejki linowej','Kolejka górska','Wyciąg narciarski','Stok narciarski','Trasa biegowa','Szlak rowerowy','Trasa spacerowa','Park narodowy',
    'Rezerwat przyrody','Wieża ciśnień','Elektrownia','Wiatraki','Farma wiatrowa','Farma','Zagroda','Obora','Stodoła','Młyn',
    'Wiatrak','Tama','Zapora','Wąwóz','Kanion','Jezioro górskie','Bagno','Mokradła','Rafa koralowa','Laguna',
    'Jaskinia lodowa','Skałki','Wspinaczkowa skała','Kamieniołom','Kopalnia','Huta','Rafineria','Stocznia','Port lotniczy','Wieża kontroli lotów',
    'Salon odlotów','Sala przylotów','Korytarz','Hol','Recepcja','Poczekalnia','Kasyno','Klub nocny'
  ],
    animals:[
    'Pies','Kot','Słoń','Pingwin','Delfin','Żyrafa','Kura','Rekin','Koń','Krowa',
    'Owca','Koza','Świnia','Królik','Chomik','Papuga','Sowa','Lis','Wilk','Niedźwiedź',
    'Panda','Tygrys','Lew','Kangur','Wąż','Żaba','Krokodyl','Żółw','Orzeł','Wieloryb',
    'Ośmiornica','Foka','Jeż','Bóbr','Wiewiórka','Dzik','Sarna','Jeleń','Łoś','Ryś',
    'Żubr','Borsuk','Kuna','Łasica','Wydra','Ropucha','Salamandra','Jaszczurka','Iguana','Kameleon',
    'Pająk','Mrówka','Pszczoła','Osa','Szerszeń','Biedronka','Motyl','Mucha','Komar','Ślimak',
    'Dżdżownica','Kret','Nietoperz','Gołąb','Wróbel','Bocian','Żuraw','Kruk','Sroka','Kaczka',
    'Gęś','Indyk','Paw','Struś','Flaming','Pelikan','Mewa','Pingwin cesarski','Niedźwiedź polarny','Renifer',
    'Wielbłąd','Dromader','Słoń afrykański','Nosorożec','Hipopotam','Zebra','Antylopa','Gepard','Lampart','Hiena',
    'Szakal','Goryl','Szympans','Orangutan','Lemur','Koala','Diabeł tasmański','Kangur rudy','Pies husky','Kot perski',
    'Biały rekin','Manta','Meduza','Krab','Homar','Krewetka','Konik morski','Ryba klaun','Pstrąg','Łosoś',
    'Karp','Sum','Szczupak','Sandacz','Dorsz','Tuńczyk','Alpaka','Lama','Osioł','Mamut',
    'Słoń indyjski','Puma','Jaguar','Pantera','Bawół','Bizon','Jak','Wół','Muflon','Koziorożec',
    'Ryba miecz','Rekin młot','Morświn','Narwal','Beluga','Delfin butlonosy','Kaszalot','Wydra morska','Lew morski','Mors',
    'Pingwin królewski','Albatros','Sęp','Jastrząb','Sokół','Puchacz','Dzięcioł','Kos','Drozd','Skowronek',
    'Jaskółka','Jerzyk','Kuropatwa','Bażant','Przepiórka','Kogut','Kura nioska','Wrona','Gawron','Czajka',
    'Bąk','Czapla','Bielik','Kania','Kormoran','Zimorodek','Płaszczka','Węgorz','Płotka','Leszcz',
    'Okon','Piranha','Arowana','Złota rybka','Gupik','Karp koi','Świerszcz','Konik polny','Pasikonik','Chrząszcz',
    'Żuk','Jelonek rogacz','Kornik','Gąsienica','Pająk krzyżak','Tarantula','Skorpion','Kleszcz','Pchła','Pluskwa',
    'Ważka','Mucha końska','Biedronka siedmiokropka','Modliszka','Karaluch','Gekon','Żmija','Kobra','Pyton','Boa',
    'Anakonda','Szop pracz','Jenot','Piesek preriowy','Świstak','Marmota','Pika','Panda czerwona'
  ],
    random:[
    'Lepszy wróbel w garści','Nie chwal dnia przed zachodem','Co dwie głowy to nie jedna','Apetyt rośnie w miarę jedzenia','Darowanemu koniowi w zęby się nie zagląda','Kto rano wstaje, temu Pan Bóg daje','Nie ma tego złego, co by na dobre nie wyszło','Strach ma wielkie oczy','Tonący brzytwy się chwyta','Kłamstwo ma krótkie nogi',
    'Jedna jaskółka wiosny nie czyni','Co nagle, to po diable','Gdzie kucharek sześć, tam nie ma co jeść','Nie wszystko złoto, co się świeci','Jak trwoga, to do Boga','Gość w dom, Bóg w dom','Kuj żelazo, póki gorące','Ręka rękę myje','Wpaść jak śliwka w kompot','Bułka z masłem',
    'Leje jak z cebra','Czuć się jak ryba w wodzie','Mieć dwie lewe ręce','Każdy kij ma dwa końce','Biednemu zawsze wiatr w oczy','Gdy kota nie ma, myszy harcują','Co z oczu, to z serca','Co cię nie zabije, to cię wzmocni','Szewc bez butów chodzi','Porywać się z motyką na słońce',
    'Nie od razu Kraków zbudowano','Wziąć byka za rogi','Nie wywołuj wilka z lasu','Kupić kota w worku','W nocy wszystkie koty są czarne','Cisza jak makiem zasiał','Burza w szklance wody','Musztarda po obiedzie','Przyszła koza do woza','Słomiany zapał',
    'Nie dla psa kiełbasa','I wilk syty, i owca cała','Nadzieja matką głupich','Mądry Polak po szkodzie','Lepszy rydz niż nic','Lepszy późno niż wcale','Bez pracy nie ma kołaczy','Nie chwal dnia przed zachodem słońca','Co dwie głowy, to nie jedna','Nie samym chlebem człowiek żyje',
    'Siedzieć jak na szpilkach','Mieć serce na dłoni','Mieć oczy dookoła głowy','Mieć łeb jak sklep','Mieć muchy w nosie','Rzucać grochem o ścianę','Robić z igły widły','Szukaj wiatru w polu','Wyszedł szydło z worka','Mleko się rozlało',
    'Nie płacz nad rozlanym mlekiem','Nie taki diabeł straszny, jak go malują','Nosił wilk razy kilka, ponieśli i wilka','Lepszy wróbel w garści niż gołąb na dachu','Jak sobie pościelesz, tak się wyśpisz','Gdzie diabeł nie może, tam babę pośle','Diabeł tkwi w szczegółach','Pal licho','Rzut beretem','Krokodyl łzy',
    'Wstać lewą nogą','Złapać wiatr w żagle','Zjeść z kimś beczkę soli','Wyjść na ludzi','Wyjść z twarzą','Dać plamę','Zrobić z siebie idiotę','Strzelić focha','Mieć pecha','Mieć szczęście jak w totka',
    'Wydawać krocie','Liczyć każdy grosz','Kasa w błoto','Wyrzucić pieniądze w błoto','Kupić za bezcen','Jak znalazł','Jak ulał','Jak w zegarku','Jak w masło','Jak w dym',
    'Jak w transie','Wziąć nogi za pas','Dać nogę','Zwinąć się','Zniknąć jak kamfora','Uciec gdzie pieprz rośnie','Wpaść z deszczu pod rynnę','Nie mój cyrk, nie moje małpy','Mieć w nosie','Mieć to gdzieś',
    'Mieć coś na końcu języka','Stanąć na głowie','Ręce opadają','Włosy stają dęba','Serce w gardle','Zrobić wielkie oczy','Otworzyć szeroko oczy','Zamknąć się w sobie','Puścić farbę','Spalić się ze wstydu',
    'Zrobić się czerwonym jak burak','Zbladnąć jak ściana','Zielony jak trawa','W czepku urodzony','W gorącej wodzie kąpany','Siedzieć jak mysz pod miotłą','Cicho jak mysz pod miotłą','Znać się jak łyse konie','Znać coś na wylot','Znać coś od podszewki',
    'Mieć nosa do interesów','Węszyć','Być na tropie','Chodzić własnymi drogami','Iść na skróty','Iść na łatwiznę','Być w czepku urodzonym','Wpaść w szał','Dostać szału','Dostać gęsiej skórki',
    'Dostać skrzydeł','Mieć pod górkę','Iść pod górkę','Stawać okoniem','Stawiać na swoim','Pójść po rozum do głowy','Mieć rozum w głowie','Mieć coś w małym palcu','Mieć złote ręce','Mieć złote serce',
    'Twardy orzech do zgryzienia','Łatwy orzech do zgryzienia','Mieć język jak brzytwę','Mieć niewyparzoną gębę','Trzymać język za zębami','Trzymać fason','Trzymać nerwy na wodzy','Zacisnąć zęby','Zacisnąć pasa','Zapiąć pas',
    'Zapiąć guziki','Mieć duszę na ramieniu','Mieć miękkie serce','Twarde serce','Zimny jak lód','Gorąca głowa','Mieć głowę w chmurach','Chodzić z głową w chmurach','Stąpać twardo po ziemi','Być na ziemi',
    'Być w siódmym niebie','Zejść na ziemię','Łapać oddech','Złapać drugi oddech','Być w formie','Być w dołku','Wpaść w dołek','Być na fali','Mieć doła','Nie mieć siły',
    'Nie mieć czasu','Czas to pieniądz','Spóźniony jak zawsze','Pędzić na złamanie karku','Zasuwać jak dziki osioł','Robić jak wół','Harować jak koń','Język giętki powie wszystko, co pomyśli głowa','Jak sobie Kuba Bogu, tak Bóg Kubie','Baba z wozu, koniom lżej',
    'Na złodzieju czapka gore','Gdzie dwóch się bije, tam trzeci korzysta','Lepszy mały deszcz niż żadna pogoda','Nie ma róży bez kolców','Co za dużo, to niezdrowo','Przez żołądek do serca','Kto pod kim dołki kopie, ten sam w nie wpada','Pokorne cielę dwie matki ssie','Na bezrybiu i rak ryba','Nie ma dymu bez ognia',
    'Kto pyta, nie błądzi','Kto nie ryzykuje, ten nie pije szampana','Co ma wisieć, nie utonie','Dobrymi chęciami piekło jest wybrukowane','Nie budź licha, gdy śpi','Wolnoć Tomku w swoim domku','Co kraj, to obyczaj','Każda potwora znajdzie swego amatora','Diabeł nie śpi','Głodnemu chleb na myśli',
    'Gdzie drwa rąbią, tam wióry lecą','Jakie drzewo, taki klin','Jaki ojciec, taki syn','Jaka matka, taka córka'
  ],
    dev:[
    'Mała konstantynopolitańczykowianeczka tańczy na moście nad Bosforem','TEST1','TEST2','TEST3','TEST4','TEST5'
  ]
  };
})();